### ISSUE TITLE
gxneur: Depends on gconf

### ISSUE THREAD

**Issue by gerasiov** [AndrewCrewKuznetsov/xneur-devel#27]
gconf will be removed from Debian (and Ubuntu as well) soon.

gconf's last release was about 5 years ago. It has been replaced by
gsettings (provided in Debian by source glib2.0 )

References
----------
https://developer.gnome.org/gio/stable/ch34.html
https://developer.gnome.org/gio/stable/GSettings.html

https://bugs.debian.org/886066

**Comment by AndrewCrewKuznetsov** [comment]
Fixed on git.
