### ISSUE TITLE
В KDE Plasma при вводе текста "скачет" фокус окна

### ISSUE THREAD

**Issue by emvaized** [AndrewCrewKuznetsov/xneur-devel#61]
1) Включаем демон;
2) Вводим любой текст -- заголовок окна постоянно "мерцает", так как при вводе каждого символа на долю секунды теряет фокус, и снова обретает;
3) Также это делает невозможным ввод текста в определенных динамических полях в системе -- например, в поисковой строке меню приложегний, или при переименовывании файла в Dolphin.

**Comment by Mingun** [comment]
Лучше запустить демон в консоли с уровнем отладки TRACE и запостить сюда релевантный вывод от печатания пары символов.

Вообще, чем больше исследую код, тем больше у меня подозрений, что основные глюки от багов в X сервере, а не в xneur. Хотя может он просто неправильно X API использует, это я еще не смотрел детально.

**Comment by emvaized** [comment]
> Лучше запустить демон в консоли с уровнем отладки TRACE и запостить сюда релевантный вывод от печатания пары символов.
> 
> Вообще, чем больше исследую код, тем больше у меня подозрений, что основные глюки от багов в X сервере, а не в xneur. Хотя может он просто неправильно X API использует, это я еще не смотрел детально.

Вполне стандартный вывод:
```
[TRA] 10:10:45 Received KeyPress 's' (event type 2)
[TRA] 10:10:45 Received KeyRelease 's' (event type 3)
[TRA] 10:10:46 Received KeyPress 's' (event type 2)
[TRA] 10:10:46 Received KeyRelease 's' (event type 3)
```

**Comment by emvaized** [comment]
На свежей установке KDE Neon проблема не наблюдается.
Скорее всего, дело было в каких-то моих настройках на предыдущей ОС -- возможно, настройки "фокус следует за мышью".
